// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCghl6DnHj94tTuqpHVOrBIwDxby9mGcog',
    appId: '1:660734934401:web:aec380e0d62b7e74633c80',
    messagingSenderId: '660734934401',
    projectId: 'aqyl-school-b2f09',
    authDomain: 'aqyl-school-b2f09.firebaseapp.com',
    storageBucket: 'aqyl-school-b2f09.appspot.com',
    measurementId: 'G-E8JWBWZS98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB82izWIONysMRdr3ShAHK7ImvVbyZMT9Y',
    appId: '1:660734934401:android:0e74aad5d6a7cb0d633c80',
    messagingSenderId: '660734934401',
    projectId: 'aqyl-school-b2f09',
    storageBucket: 'aqyl-school-b2f09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2NvehoE2DGOyWShUtlKQQOogO7GRKbDU',
    appId: '1:660734934401:ios:8ea2362c105be8b7633c80',
    messagingSenderId: '660734934401',
    projectId: 'aqyl-school-b2f09',
    storageBucket: 'aqyl-school-b2f09.appspot.com',
    iosClientId: '660734934401-ncea3jufn1h52plugdodqnah9q8q560o.apps.googleusercontent.com',
    iosBundleId: 'com.example.aqylSchool',
  );
}
